- name: Check if google-chrome is installed
  when: ansible_facts['os_family'] == "Debian"
  shell: command -v google-chrome
  register: chrome_exists
  ignore_errors: true


- name: Install google-chrome dependencies
  when: ansible_facts['os_family'] == "Debian" and chrome_exists is failed
  become: true
  apt:
    name: libu2f-udev
    update_cache: true

- name: Download google-chrome
  when: ansible_facts['os_family'] == "Debian" and chrome_exists is failed
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/chrome.deb

- name: Install google chrome from deb file
  when: ansible_facts['os_family'] == "Debian" and chrome_exists is failed
  become: true
  apt: deb="/tmp/chrome.deb"
