- name: Check if syncthing installed
  shell: command -v syncthing
  register: syncthing_exists
  ignore_errors: true

- name: Install syncthing on arch
  when: ansible_distribution == "Archlinux" and syncthing_exists is failed
  include_tasks: syncthing_arch.yml

- name: Install syncthing on debian
  include_tasks: syncthing_debian.yml
  when: ansible_facts['os_family'] == "Debian" and syncthing_exists is failed
