- name: Check if sxhkd installed
  shell: command -v sxhkd
  register: sxhkd_exists
  ignore_errors: true

- name: Install sxhkd
  become: true
  when:
    - ansible_facts['os_family'] == "Debian"
    - sxhkd_exists is failed
  apt:
    update_cache: true
    name: sxhkd

- name: Copy autostart item
  when:
    - ansible_facts['distribution'] == "Pop!_OS"
    - sxhkd_exists is failed
  copy:
    src: "autostart/sxhkd.desktop"
    dest: "{{ lookup('env', 'HOME') }}/.config/autostart/"
