- name: Check if rofi installed
  shell: command -v rofi
  register: rofi_exists
  ignore_errors: true

- name: Install rofi
  include_tasks: rofi.yml
  when:
    - ansible_facts['os_family'] == "Debian"
    - rofi_exists is failed

- name: Install rofi-emoji
  include_tasks: rofi-emoji.yml
  when:
    - ansible_facts['os_family'] == "Debian"
    - rofi_exists is failed
