- name: Install 1password with homebrew
  community.general.homebrew:
    path: "{{ lookup('vars', 'brew_path') }}"
    name: "{{ item }}"
  ignore_errors: true
  with_items:
    - 1password
    - 1password-cli
