- name: Check if 1password is installed
  when: ansible_system == "Linux"
  shell: command -v 1password
  register: onepassword_exists
  ignore_errors: true

- name: Download 1Password deb
  when: ansible_facts['os_family'] == "Debian" and onepassword_exists is failed
  get_url:
    url="https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb"
    dest="/tmp/1password.deb"

- name: Install 1Password from deb file
  when: ansible_facts['os_family'] == "Debian" and onepassword_exists is failed
  become: true
  apt: deb="/tmp/1password.deb"
