- name: Install 1Password on arch
  include_tasks: 1password_arch.yml
  when: ansible_facts['distribution'] == "Archlinux"

- name: Install 1Password on mac
  include_tasks: 1password_mac.yml
  when: ansible_distribution == "MacOSX"
