- name: Check if zsh installed
  shell: command -v zsh
  register: zsh_exists
  ignore_errors: true

- name: Install zsh and shell related packages on Arch
  become: true
  pacman:
    name:
      - neovim
      - bat
      - eza
      - tmux
      - zsh
