- name: Creates ssh directory
  become_user: "{{ lookup('vars', 'username') }}"
  file:
    path: "{{ lookup('env', 'HOME') }}/.ssh"
    state: directory

- name: Decrypt ssh config file
  become_user: "{{ lookup('vars', 'username') }}"
  copy:
    src: "./config"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/config"
    decrypt: yes
