- name: Install global npm packages
  become_user: "{{ lookup('vars', 'username') }}"
  environment:
    NPM_CONFIG_PREFIX: "{{ lookup('env', 'HOME') }}/.config/npm-global"
  npm:
    name: "{{item}}"
    global: yes
  with_items:
    - 'yarn'
    - 'typescript'
    - 'ts-node'
    - 'neovim'
    - '@gridsome/cli'
    - 'yaml-language-server'
    - 'vim-language-server'
    - 'vscode-langservers-extracted'
    - 'graphql-language-service-cli'
    - 'apollo'
    - 'vscode-langservers-extracted'
    - 'diff-so-fancy'
  tags:
    - node
    - npm
