- name: Check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: true
  tags:
    - rust

- name: Install rust (and cargo)
  become: true
  when: ansible_facts['distribution'] == "Archlinux" and cargo_exists is failed
  pacman:
    name:
      - rust
  tags:
    - rust

- name: Install cargo packages
  when: cargo_exists
  community.general.cargo:
    name:
      - stylua
  tags:
    - rust
