- name: Check if docker installed
  shell: command -v node
  register: docker_exists
  ignore_errors: true
  tags:
    - services
    - docker

- name: Install docker on Arch
  become: true
  when: ansible_distribution == "Archlinux" and docker_exists is failed
  pacman:
    name: docker
  tags:
    - services
    - docker

- name: Check if docker installed
  shell: command -v node
  register: docker_exists
  ignore_errors: true
  tags:
    - services
    - docker

- name: Start docker service
  become: true
  when: ansible_distribution == "Archlinux" and docker_exists
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  tags:
    - services
    - docker

- name: Adding my user to docker group
  when: ansible_system == "Linux"
  become: true
  user:
    name: "{{ lookup('vars', 'username') }}"
    groups: docker
    append: yes
  tags:
    - services
    - docker
