- name: Debug print out the espanso_path var
  debug: msg="{{ lookup('vars', 'espanso_path') }}"
  tags:
    - debug
    - espanso

- name: Ensure espanso directory exists.
  become_user: "{{ lookup('vars', 'username') }}"
  file:
    dest: "{{ lookup('vars', 'espanso_path') }}"
    mode: 0700
    state: directory
  tags:
    - espanso

- name: Install espanso conf files
  become_user: "{{ lookup('vars', 'username') }}"
  copy:
    src: "./espanso/"
    dest: "{{ lookup('vars', 'espanso_path') }}"
    decrypt: yes
  tags:
    - espanso
