- name: Check if syncthing installed
  shell: command -v node
  register: syncthing_exists
  ignore_errors: true
  tags:
    - services
    - syncthing

- name: Install syncthing on Arch
  become: true
  when: ansible_distribution == "Archlinux" and syncthing_exists is failed
  pacman:
    name: syncthing
  tags:
    - services
    - syncthing

- name: Start syncthing service
  become: true
  when: ansible_distribution == "Archlinux" and syncthing_exists
  ansible.builtin.systemd:
    name: "syncthing@{{ lookup('vars', 'username') }}.service"
    state: started
    enabled: true
  tags:
    - services
    - syncthing
