- name: Install nvim dependencies on Debian systems
  when: ansible_facts['os_family'] == "Debian"
  become: true
  apt:
    name:
      - ninja-build
      - gettext
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake

- name: Install nvim dependencies on Arch
  when: ansible_facts['distribution'] == "Archlinux"
  become: true
  pacman:
    name:
      - base-devel
      - cmake
      - unzip
      - ninja
      - tree-sitter
      - curl

- name: Install nvim dependencies on Mac
  when: ansible_distribution == 'MacOSX'
  homebrew:
    path: "{{ lookup('vars', 'brew_path') }}"
    name:
      - ninja
      - libtool
      - automake
      - cmake
      - pkg-config
      - gettext
      - curl

- name: Remove neovim
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/packages/neovim"
    state: absent

- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/packages/neovim"
    version: v0.9.1

- name: Build neovim
  args:
    chdir: "{{ lookup('env', 'HOME') }}/packages/neovim"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ lookup('vars', 'brew_path') }}"
  shell: "make -j 8 CMAKE_BUILD_TYPE=RelWithDebInfo"

- name: Install neovim
  become: true
  args:
    chdir: "{{ lookup('env', 'HOME') }}/packages/neovim"
  shell: "make install"
