### Mac ###

- name: Check anki Application exists
  when: ansible_distribution == "MacOSX"
  stat:
    path: /Applications/Anki.app
  register: anki_exists
  tags:
    - anki
    - packages

- name: Download anki dmg
  when: ansible_distribution == "MacOSX" and not anki_exists.stat.exists
  get_url:
    url: https://github.com/ankitects/anki/releases/download/2.1.49/anki-2.1.49-mac.dmg
    dest: "{{ lookup('env', 'HOME') }}/Downloads/"
  tags:
    - anki
    - packages

- name: Mount anki dmg
  when: ansible_distribution == "MacOSX" and not anki_exists.stat.exists
  shell: hdiutil attach "{{ lookup('env', 'HOME') }}/Downloads/anki-2.1.49-mac.dmg"
  tags:
    - anki
    - packages

- name: Copy anki app from dmg
  when: ansible_distribution == "MacOSX" and not anki_exists.stat.exists
  shell: cp -r /Volumes/Anki/Anki.app /Applications/
  tags:
    - anki
    - packages

- name: Unmount anki dmg
  when: ansible_distribution == "MacOSX" and not anki_exists.stat.exists
  shell: hdiutil detach /Volumes/Anki
  tags:
    - anki
    - packages

- name: Remove dmg
  when: ansible_distribution == "MacOSX" and not anki_exists.stat.exists
  file:
    path: "{{ lookup('env', 'HOME') }}/Downloads/anki-2.1.49-mac.dmg"
    state: absent
  tags:
    - anki
    - packages
