- name: Install Homebrew formulae arm64
  when: ansible_facts['distribution'] == "MacOSX" and brew_exists and ansible_architecture == "arm64"
  community.general.homebrew:
    name: "{{ item }}"
  with_items: "{{ homebrew_formulae_arm64.stdout_lines }}"
  ignore_errors: true
  tags:
    - homebrew
    - packages

- name: Install Homebrew formulae x86
  when: ansible_facts['distribution'] == "MacOSX" and brew_exists and ansible_architecture == "x86_64"
  community.general.homebrew:
    name: "{{ item }}"
  with_items: "{{ homebrew_formulae_x86.stdout_lines }}"
  ignore_errors: true
  tags:
    - homebrew
    - packages

- name: Install Homebrew casks
  when: ansible_facts['distribution'] == "MacOSX" and brew_exists and ansible_architecture == "arm64"
  community.general.homebrew:
    name: "{{ item }}"
  with_items: "{{ homebrew_casks.stdout_lines }}"
  ignore_errors: true
  tags:
    - homebrew
    - packages
