- name: Update git submodules
  shell: git submodule update --init --recursive

- name: Ensure awesome config directory exists.
  when: ansible_system == "Linux"
  become_user: "{{ lookup('vars', 'username') }}"
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/awesome"
    state: directory

- name: Install Dotfiles
  become_user: "{{ lookup('vars', 'username') }}"
  ignore_errors: true
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles"
    target: dotbot-run
