- name: Get APT package list
  when: ansible_facts['distribution'] == "Pop!_OS"
  command:
    cmd: cat ./packages/apt.txt
  register: apt_packages
  tags:
    - apt
    - packages

- name: Install System Packages
  become: true
  when: ansible_facts['distribution'] == "Pop!_OS"
  apt:
    name: "{{ apt_packages.stdout_lines }}"
  tags:
    - apt
    - packages
