- name: Check if brillo is installed
  when: ansible_system == "Linux"
  shell: command -v brillo
  register: brillo_exists
  ignore_errors: true
  tags:
    - build-packages
    - brillo

- name: Clone brillo
  when: ansible_system == "Linux" and brillo_exists is failed
  ansible.builtin.git:
    repo: 'https://github.com/CameronNemo/brillo.git'
    dest: "{{ lookup('env', 'HOME') }}/packages/brillo"
    update: yes
    version: master
  tags:
    - build-packages
    - brillo

- name: Build and install brillo
  when: ansible_system == "Linux" and brillo_exists is failed
  become: true
  args:
    chdir: "{{ lookup('env', 'HOME') }}/packages/brillo"
  shell: "make && make install"
  tags:
    - build-packages
    - brillo
