- name: Update git submodules
  shell: git submodule update --init --recursive
  tags:
    - dotfiles

- name: Install Dotfiles
  become_user: "{{ lookup('vars', 'username') }}"
  ignore_errors: true
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles"
    target: dotbot-run
  tags:
    - dotfiles
