- name: Add flathub flatpak repo
  when: ansible_facts['distribution'] == "Pop!_OS"
  become_user: "{{ lookup('vars', 'username') }}"
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  tags:
    - flatpak
    - packages

- name: Get flatpak package list
  when: ansible_facts['distribution'] == "Pop!_OS"
  command:
    cmd: cat ./packages/flatpak.txt
  register: flatpak_packages
  tags:
    - flatpak
    - packages

- name: Install flatpak packages
  when: ansible_facts['distribution'] == "Pop!_OS"
  become_user: "{{ lookup('vars', 'username') }}"
  community.general.flatpak:
    name: "{{item}}"
    state: present
    method: user
  with_items: "{{flatpak_packages.stdout_lines}}"
  tags:
    - flatpak
    - packages
