- name: Check flatpak installed
  shell: command -v flatpak
  ignore_errors: true
  register: flatpak_exists
  tags:
    - flatpak
    - packages

- name: Install flatpak
  become: true
  when: ansible_facts['distribution'] == "Archlinux" and flatpak_exists is failed
  pacman:
    name: flatpak
  tags:
    - flatpak
    - packages

- name: Add flathub flatpak repo
  when: ansible_system == "Linux" and flatpak_exists
  become_user: "{{ lookup('vars', 'username') }}"
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  tags:
    - flatpak
    - packages

- name: Get flatpak package list
  when: ansible_system == "Linux" and flatpak_exists
  command:
    cmd: cat ./packages/flatpak.txt
  register: flatpak_packages
  tags:
    - flatpak
    - packages

- name: Install flatpak packages
  when: ansible_system == "Linux" and flatpak_exists
  become_user: "{{ lookup('vars', 'username') }}"
  community.general.flatpak:
    name: "{{item}}"
    state: present
    method: user
  with_items: "{{flatpak_packages.stdout_lines}}"
  tags:
    - flatpak
    - packages
