- name: Check if miniconda already installed
  stat: path={{ conda_path }}/bin/conda
  register: bin_conda
  changed_when: bin_conda.stat.exists == False
  tags:
    - python
    - miniconda

- name: Download miniconda installer
  get_url:
    url: "{{ miniconda_url }}"
    dest: /tmp/miniconda.sh
    mode: 0755
  register: miniconda_downloaded
  when: bin_conda.stat.exists == False
  tags:
    - python
    - miniconda

- name: install miniconda
  shell: "/tmp/miniconda.sh -b -p {{ conda_path }} creates={{ conda_path }} executable=/bin/bash"
  register: miniconda_installed
  when: miniconda_downloaded
  # notify:
  #   - remove miniconda setup script
  #   - update conda to latest version
  tags:
    - python
    - miniconda
