- name: Install nvim dependencies on Debian systems
  when: ansible_facts['os_family'] == "Debian"
  become: true
  apt:
    name:
      - ninja-build
      - gettext
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
  tags:
    - nvim

- name: Remove neovim
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/packages/neovim"
    state: absent
  tags:
    - nvim

- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/packages/neovim"
  tags:
    - nvim

- name: Build neovim
  args:
    chdir: "{{ lookup('env', 'HOME') }}/packages/neovim"
  shell: "make -j 8 CMAKE_BUILD_TYPE=RelWithDebInfo"
  tags:
    - nvim

- name: Install neovim
  become: true
  args:
    chdir: "{{ lookup('env', 'HOME') }}/packages/neovim"
  shell: "make install"
  tags:
    - nvim
