- name: Install nvim dependencies on Debian systems
  when: ansible_facts['os_family'] == "Debian"
  become: true
  apt:
    name:
      - ninja-build
      - gettext
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
  tags:
    - nvim

- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/packages/neovim"
    update: yes
  tags:
    - nvim

- name: Fetch Neovim
  # The next step will fail without --force since they move nightly tag often
  # I am not sure how to force the next step, so this is the best I have
  shell: "git fetch --tags origin --force"
  args:
    chdir: "{{ lookup('env', 'HOME') }}/packages/neovim"
  # don't fail if the repo does not exist
  ignore_errors: true
  tags:
    - nvim

- name: Build neovim
  args:
    chdir: "{{ lookup('env', 'HOME') }}/packages/neovim"
  shell: "make CMAKE_BUILD_TYPE=RelWithDebInfo"
  tags:
    - nvim

- name: Install neovim
  become: true
  args:
    chdir: "{{ lookup('env', 'HOME') }}/packages/neovim"
  shell: "make install"
  tags:
    - nvim
