- name: Get pacman package list
  when: ansible_facts['distribution'] == "Archlinux"
  command:
    cmd: cat ./packages/pacman.txt
  register: pacman_packages
  tags:
    - pacman
    - packages

- name: Install System Packages
  become: true
  when: ansible_facts['distribution'] == "Archlinux"
  pacman: name={{item}}
  with_items: "{{ pacman_packages.stdout_lines }}"
  tags:
    - pacman
    - packages

- name: Install sound firmeware for Thinkpad T14
  become: true
  when: ansible_facts['product_version'] == "ThinkPad T14 Gen 2i"
  pacman:
    name: sof-firmware
  tags:
    - pacman
    - packages
