- name: Check is pipx installed
  shell: command -v pipx
  register: pipx_exists
  ignore_errors: true
  tags:
    - pipx

########## PIPX INSTALL ##########

- name: Install pipx mac
  homebrew:
    name: pipx
    state: present
    path: "{{ lookup('vars', 'brew_path') }}/brew"
  ignore_errors: true
  when: pipx_exists is failed and ansible_distribution == "MacOSX"
  tags:
    - pipx

- name: Post install pipx on Mac
  command:
    cmd: "{{ lookup('vars', 'brew_path') }}/pipx ensurepath"
  when: pipx_exists and ansible_distribution == "MacOSX"
  tags:
    - pipx

- name: Install pipx on Arch
  when: pipx_exists is failed and ansible_distribution == "Archlinux"
  pip:
    name: pipx
  tags:
    - pipx

- name: Install pipx on Debian
  when: pipx_exists is failed and ansible_facts['os_family'] == "Debian"
  shell: python3 -m pip install --user -U pipx
  tags:
    - pipx

- name: Post install pipx on Debian
  command:
    cmd: pipx ensurepath
  when: pipx_exists and ansible_facts['os_family'] == "Debian"
  tags:
    - pipx

########## PIPX PACKAGES ##########

- name: Install pipx packages
  command:
    cmd: pipx install {{ item }}
  with_items:
    - python-lsp-server[all]
    - aws-sso-util
  when: pipx_exists
  tags:
    - pipx
