- name: check python is in update-alternatives
  when: ansible_facts['os_family'] == "Debian"
  shell: update-alternatives --query python
  register: python_alternative_exists
  ignore_errors: true
  tags:
    - python

- name: set python3 as default python
  when: ansible_facts['os_family'] == "Debian" and python_alternative_exists is failed
  become: true
  shell: update-alternatives --install /usr/bin/python python /usr/bin/python3 1
  tags:
    - python

- name: Check conda installed
  command:
    cmd: command -v conda
  ignore_errors: true
  register: conda_exists
  tags:
    - python

- name: Check Pyenv installed
  command:
    cmd: command -v pyenv
  ignore_errors: true
  register: pyenv_exists
  tags:
    - python

- name: Install mac pyenv dependencies
  become_user: "{{ lookup('vars', 'username') }}"
  when: ansible_distribution == "MacOSX" and pyenv_exists is failed
  homebrew:
    name: "{{item}}"
    state: present
    path: "{{ lookup('vars', 'brew_path') }}/brew"
  with_items:
    - readline
    - xz
    - openssl
  tags:
    - python

- name: Install python version 3.9.9 with pyenv
  become_user: "{{ lookup('vars', 'username') }}"
  when: pyenv_exists
  command: pyenv install -f 3.9.9
  ignore_errors: true
  tags:
    - python

- name: Set Python 3.9.9 as global version
  become_user: "{{ lookup('vars', 'username') }}"
  when: pyenv_exists
  command: pyenv global 3.9.9
  ignore_errors: true
  tags:
    - python

- name: Ensure conda envs directory exists.
  become_user: "{{ lookup('vars', 'username') }}"
  file:
    dest: "{{ lookup('vars', 'conda_path') }}/envs"
    mode: 0700
    state: directory
    recurse: true
  tags:
    - python

- name: Update conda
  become_user: "{{ lookup('vars', 'username') }}"
  when: conda_exists
  command: conda update conda -y
  tags:
    - python

- name: Create conda neovim environment
  become_user: "{{ lookup('vars', 'username') }}"
  when: conda_exists
  command: "{{item}}"
  with_items:
    - "conda create -p {{ lookup('vars', 'conda_path') }}/envs/neovim-python-3 python=3.8"
  tags:
    - python

- name: Pip install pynvim
  become_user: "{{ lookup('vars', 'username') }}"
  pip:
    name: pynvim
    executable: "{{item}}"
    state: latest
  with_items:
    - "{{ lookup('vars', 'conda_path') }}/envs/neovim-python-3/bin/pip"
  tags:
    - python
