- name: Check if zsh installed
  shell: command -v zsh
  register: zsh_exists
  ignore_errors: true
  tags:
    - shell

- name: Install ZSH on Arch
  become: true
  pacman: name=zsh
  when: ansible_facts['distribution'] == "Archlinux" and zsh_exists is failed
  tags:
    - shell

- name: Install ZSH on Debian systems
  become: true
  apt:
    pkg:
      - zsh
  when: ansible_facts['os_family'] == "Debian" and zsh_exists is failed
  tags:
    - shell

- name: Change shell to zsh
  become_user: root
  shell: chsh -s $(which zsh)
  tags:
    - shell

- name: check if starship installed
  shell: command -v starship
  register: starship_exists
  ignore_errors: true
  tags:
    - shell
    - starship

- name: Download starship installer
  when: starship_exists is failed
  get_url:
    url: https://starship.rs/install.sh
    dest: "{{ lookup('env', 'HOME') }}/install-starship.sh"
    mode: '0755'
  tags:
    - shell
    - starship

- name: Install Starship
  when: starship_exists is failed
  command: "{{ lookup('env', 'HOME') }}/install-starship.sh -y"
  tags:
    - shell
    - starship

- name: Remove starship installer
  when: starship_exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/install-starship.sh"
    state: absent
  tags:
    - shell
    - starship

- name: Install shell related packages on Arch
  become: true
  pacman:
    name:
      - bat
      - exa
  when: ansible_facts['distribution'] == "Archlinux"
  tags:
    - shell

- name: Install shell related packages on Debian systems
  become: true
  apt:
    pkg:
      - exa
      - bat
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - shell

- name: Creates packages directory
  become_user: "{{ lookup('vars', 'username') }}"
  file:
    path: "{{ lookup('env', 'HOME') }}/packages"
    state: directory
  tags:
    - dotfiles
    - shell

- name: Cloning fzf
  become_user: "{{ lookup('vars', 'username') }}"
  ansible.builtin.git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: "{{ lookup('env', 'HOME') }}/packages/fzf"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
    depth: 1
  tags:
    - dotfiles
    - shell

- name: Decrypt ssh config file
  become_user: "{{ lookup('vars', 'username') }}"
  copy:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/ansible/ssh/config"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/config"
    decrypt: yes
  tags:
    - shell
    - ssh
