- name: Ensure .ssh directory exists.
  become_user: "{{ lookup('vars', 'username') }}"
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - ssh

- name: Install ssh private key
  become_user: "{{ lookup('vars', 'username') }}"
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    decrypt: yes
    mode: 0600
  tags:
    - ssh

- name: Install ssh public key
  become_user: "{{ lookup('vars', 'username') }}"
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    decrypt: yes
  tags:
    - ssh
