- name: Install trackpad conf
  become: true
  when: ansible_facts['distribution'] == "Archlinux"
  copy:
    src: "./system/xorg/30-touchpad.conf"
    dest: "/etc/X11/xorg.conf.d/30-touchpad.conf"
    decrypt: yes
    mode: 0644
  tags:
    - system

- name: Set Pop!_OS workspace keybindings
  when: ansible_facts['distribution'] == "Pop!_OS"
  shell: "{{ lookup('env', 'HOME') }}/.dotfiles/ansible/scripts/pop_os_workspace_keybindings.sh"
  tags:
    - system
