- name: Symlink python3 to python
  become: true
  when: ansible_facts['os_family'] == "Debian"
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link

- name: Install poetry
  include_tasks: poetry.yml
  tags:
    - poetry

- name: Install miniconda and create nvim environment
  include_tasks: miniconda.yml
  tags:
    - conda
    - nvim

- name: Install pyenv
  include_tasks: pyenv.yml
  tags:
    - pyenv
