- name: Setup node and npm directories
  include_tasks: node_global.yml

- name: Install node on debian
  include_tasks: node_debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Install node on arch
  include_tasks: node_arch.yml
  when: ansible_facts['distribution'] == "Archlinux"

- name: Install node on mac
  include_tasks: node_mac.yml
  when: ansible_distribution == "MacOSX"

- name: Install N and global npm packages
  include_tasks: npm.yml
