- name: Check if node installed
  shell: command -v node
  register: node_exists
  ignore_errors: true

- name: Check if n installed
  shell: command -v n
  register: n_exists
  ignore_errors: true

- name: Creates npm-global directory
  become_user: "{{ lookup('vars', 'username') }}"
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/npm-global"
    state: directory

- name: Creates n directory
  become_user: "{{ lookup('vars', 'username') }}"
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/n"
    state: directory
