- name: Install desired version of Node using fnm
  when: ansible_facts['distribution'] == 'MacOSX'
  become_user: "{{ lookup('vars', 'username') }}"
  shell: eval "$(fnm env)" && fnm install 24 && fnm default 24
  args:
    executable: /bin/bash
  environment:
    FNM_DIR: "{{ lookup('env', 'HOME') }}/.local/share/fnm"
