- name: Install realtime-privileges package
  when: ansible_system == "Linux"
  become: true
  pacman:
    name: realtime-privileges
  tags:
    - system
    - audio

- name: Ensure group "realtime" exists
  when: ansible_distribution == "Archlinux"
  become: true
  group:
    name: realtime
    state: present
  tags:
    - system
    - audio

- name: Add my user to audio and realtime groups
  when: ansible_distribution == "Archlinux"
  become: true
  user:
    name: "{{ lookup('vars', 'username') }}"
    groups: audio, realtime
    append: yes
  tags:
    - system
    - audio

- name: Reduce swappiness
  when: ansible_distribution == "Archlinux"
  become: true
  lineinfile:
    path: /etc/sysctl.d/99-swappiness.conf
    line: "vm.swappiness=10"
    create: true
  tags:
    - system
    - audio

- name: Check if yay is installed
  shell: command -v yay
  register: yay_exists
  ignore_errors: true
  tags:
    - system
    - audio

- name: Check if tuned is installed
  shell: command -v tuned
  register: tuned_exists
  ignore_errors: true
  tags:
    - system
    - audio

- name: Install tuned
  when:
    - ansible_facts['distribution'] == "Archlinux"
    - yay_exists
    - tuned_exists is failed
  shell: yay -S --noconfirm tuned
  tags:
    - system
    - audio

- name: Check if tuned is installed (again, after install)
  shell: command -v tuned
  register: tuned_exists
  ignore_errors: true
  tags:
    - system
    - audio

- name: Start tuned service
  become: true
  when: ansible_distribution == "Archlinux" and tuned_exists
  ansible.builtin.systemd:
    name: tuned
    state: started
    enabled: true
  tags:
    - services
    - audio
