- name: Check if docker installed
  shell: command -v docker
  register: docker_exists
  ignore_errors: true

- name: Install docker on debian
  include_tasks: docker_debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Add user to docker group
  become: true
  when:
    - ansible_system == "Linux"
    - docker_exists is failed
  ansible.builtin.user:
    name: "{{ lookup('vars', 'username') }}"
    groups: docker
    append: yes
