# Remap prefix to a
set -g prefix C-a
bind C-a send-prefix
unbind C-b

# reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "Tmux conf reloaded!"

set-option -g history-limit 10000

bind | split-window -h
bind - split-window -v

# don't rename windows automatically
set-option -g allow-rename off

set -sg escape-time 1
set -g base-index 1
setw -g pane-base-index 1

# set vi keys for copy mode
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Terminal type configuration
set -g default-terminal 'screen-256color'

# autoread support
set-option -g focus-events on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'fabioluciano/tmux-tokyo-night'
set -g @plugin 'catppuccin/tmux'

# ------- smart-vim-splits --------
set -g @plugin 'mrjones2014/smart-splits.nvim'

# Optional configurations with their default values if omitted:
set -g @smart-splits_no_wrap '' # to disable wrapping. (any value disables wrapping)

set -g @smart-splits_move_left_key  'C-h' # key-mapping for navigation.
set -g @smart-splits_move_down_key  'C-j' #  --"--
set -g @smart-splits_move_up_key    'C-k' #  --"--
set -g @smart-splits_move_right_key 'C-l' #  --"--

set -g @smart-splits_resize_left_key  'M-h' # key-mapping for resizing.
set -g @smart-splits_resize_down_key  'M-j' #  --"--
set -g @smart-splits_resize_up_key    'M-k' #  --"--
set -g @smart-splits_resize_right_key 'M-l' #  --"--

set -g @smart-splits_resize_step_size '3' # change the step-size for resizing.

# ----------- theme -----------

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "slanted"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-left "#{E:@catppuccin_status_session}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
