echo "Hello from .zshrc"

stty stop undef # Stops Ctrl-s from freezing the terminal

unsetopt BEEP

export COLORTERM=truecolor
export TMUX_CONFIG="$HOME/.config/tmux/.tmux.conf"
export TEMP_DIR="/tmp"

# removes auto highlight on paste
zle_highlight=('paste:none')

DOTFILES_DIR="$HOME/.dotfiles"
[ -f "$DOTFILES_DIR/aliases.sh" ] && source "$DOTFILES_DIR/aliases.sh"
[ -f "$DOTFILES_DIR/functions.sh" ] && source "$DOTFILES_DIR/functions.sh"

# Basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)		# Include hidden files.

zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
zsh_add_plugin "hlissner/zsh-autopair"

source $ZDOTDIR/zsh-vim-mode

# TODO: Keep an eye out for a different `--no-quarantine` solution.
# Currently, you can't do `brew bundle --no-quarantine` as an option.
# https://github.com/Homebrew/homebrew-bundle/issues/474
export HOMEBREW_CASK_OPTS="--no-quarantine --no-binaries"

# Handle Mac architectures and brew paths
if [[ "$OSTYPE" == "darwin"* ]]; then
	CPU=$(uname -p)
	if [[ "$CPU" == "arm" ]]; then
		export BREWPATH="/opt/homebrew/bin"
		export PATH="$BREWPATH:$PATH"
		CONDA_PATH="/opt/homebrew/anaconda3"
	else
		export BREWPATH="/usr/local/bin"
		export PATH="$BREWPATH:$PATH"
		CONDA_PATH="/usr/local/anaconda3"
	fi
	export PATH=$(brew --prefix)/opt/llvm/bin/:$PATH
fi

export TERM=xterm-256color
export EDITOR=nvim
export TMUX_CONFIG="$HOME/.config/tmux/.tmux.conf"
export TEMP_DIR="/tmp"
export N_PREFIX="$HOME/.config/n"

export PATH="$N_PREFIX/bin:$PATH"

[ -f /opt/homebrew/etc/profile.d/autojump.sh ] && . /opt/homebrew/etc/profile.d/autojump.sh

############### ############## ############## ##############

[ -f ~/packages/fzf/shell/completion.zsh ] && source ~/packages/fzf/shell/completion.zsh
[ -f ~/packages/fzf/shell/key-bindings.zsh ] && source ~/packages/fzf/shell/key-bindings.zsh

HISTSIZE=99999
HISTFILESIZE=999999
SAVEHIST=$HISTSIZE
HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history

# Change cursor shape for different vi modes.
function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] ||
     [[ $1 = 'block' ]]; then
    echo -ne '\e[1 q'
  elif [[ ${KEYMAP} == main ]] ||
       [[ ${KEYMAP} == viins ]] ||
       [[ ${KEYMAP} = '' ]] ||
       [[ $1 = 'beam' ]]; then
    echo -ne '\e[5 q'
  fi
}
zle -N zle-keymap-select

zle-line-init() {
    zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
    echo -ne "\e[5 q"
}
zle -N zle-line-init
echo -ne '\e[5 q' # Use beam shape cursor on startup.
preexec() { echo -ne '\e[5 q' ;} # Use beam shape cursor for each new prompt.

# # Use lf to switch directories and bind it to ctrl-o
# lfcd () {
#     tmp="$(mktemp)"
#     lf -last-dir-path="$tmp" "$@"
#     if [ -f "$tmp" ]; then
#         dir="$(cat "$tmp")"
#         rm -f "$tmp"
#         [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
#     fi
# }
# bindkey -s '^o' 'lfcd\n'

# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/__tabtab.zsh ]] && . ~/.config/tabtab/__tabtab.zsh || true

# Added by serverless binary installer
export PATH="$HOME/.serverless/bin:$PATH"

export ANKI_DIR="~/Library/Application\ Support/Anki2"
export ANKI_PROFILE="danny"

# # python penv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

if command -v pyenv 1>/dev/null 2>&1; then
	eval "$(pyenv init --path)"
fi

[ -f "$HOME/sync/scripts/aws/aws.sh" ] && source "$HOME/sync/scripts/aws/aws.sh"

jdk() {
	version=$1
	export JAVA_HOME=$(/usr/libexec/java_home -v"$version");
	java -version
 }

export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

[ -f "/Users/dannykeig/.ghcup/env" ] && source "/Users/dannykeig/.ghcup/env" # ghcup-env

if [[ "$OSTYPE" == "linux"* ]]; then
	ANKI_PATH="$HOME/packages/anki-2.1.35-linux-amd64/bin"
	export PATH="$ANKI_PATH:$PATH"
fi

eval "$(starship init zsh)"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("$CONDA_PATH/conda" 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$CONDA_PATH/etc/profile.d/conda.sh" ]; then
        . "$CONDA_PATH/etc/profile.d/conda.sh"
    else
        export PATH="$CONDA_PATH/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
